nireports/__init__.py
setup.cfg

MAINT: Integrated isort

---

pyproject.toml
setup.cfg

MAINT: Added black to dev requirements

---

CONTRIBUTING.md

Copied [fMRIPre's contribution guidelines](https://github.com/nipreps/fmriprep/blob/master/CONTRIBUTING.md) template to link to the nipreps project's address (resolves #18).

MAINT: Created contribution guidelines

---

.pre-commit-config.yaml
setup.cfg

MAINT: Created pre-commit hook

---

.gitignore
docs/Makefile
docs/conf.py
docs/index.rst
docs/installation.rst
docs/make.bat
docs/modules/modules.rst
docs/modules/nireports.reportlets.rst
docs/modules/nireports.rst
docs/overview.rst
docs/quickstart.rst
setup.cfg

Added basic documentation generation infrastructure

---

.readthedocs.yaml

Created RTD configuration file trying to fix #31.

RTD build fix

---

README.rst

Converted README to rst

---

.github/workflows/build_test_deploy.yml

Trying to fix #36 (scipy installation failure for Win10/x86/Python3.10).

Fixing 32-bit Windows with Python 3.10 build

---

.maint/MAINTAINERS.md

- Add Elodie Savary
- modify affiliation of Céline Provins 
- switch names and last names

Fix: updated maintainers.md

---

nireports/interfaces/__init__.py
nireports/interfaces/base.py
nireports/interfaces/fmri.py
nireports/interfaces/mosaic.py
nireports/interfaces/nuisance.py

ENH: API refactor of *Nipype* interfaces

---

nireports/assembler/data/default.yml
nireports/assembler/data/tests/work/reportlets/nireports/sub-01/figures/sub-01_desc-reconall_T1w.svg
nireports/assembler/report.py
nireports/assembler/reportlet.py

ENH: Allow CSS styling of reportlets in bootstrap file

---

.circleci/config.yml
pyproject.toml

Codecov pulled their PyPI package.

CI: Purge codecov Python package

---

nireports/interfaces/dmri.py
nireports/reportlets/modality/dwi.py

Adds a plot like this:
To be added into MRIQC.
cc/ @arokem

ENH: Add a new DWI heatmap for quality control

---

nireports/interfaces/mosaic.py
nireports/reportlets/mosaic.py

FIX: Calculation of aspect ratio of mosaics

---

nireports/assembler/report.py
nireports/interfaces/reporting/base.py
nireports/reportlets/mosaic.py
nireports/reportlets/nuisance.py
nireports/reportlets/xca.py

Also manually changed a few traditional string interpolations to f-strings.

fix: assorted pyupgrade suggestions

---

nireports/assembler/report.py
nireports/assembler/tests/test_report.py

This adds label filtering for the session entity, similar to subject, and a test to verify.

ENH: Add session filtering to report generation

---

README.rst

ENH: Add CI badges to README

---

README.rst

ENH: Add PyPI badge to README

---

README.rst

ENH: Add license badge to README

---

.maint/update_authors.py

Fix style in `update_authors.py` following commits https://github.com/nipreps/eddymotion/commit/b09cbd134441c80dc666d6ba115c023d7c3a70f1 and
https://github.com/nipreps/eddymotion/commit/d8955fe91151124622e811b091fcdd61f4c815cf

STYLE: Fix style in `update_authors.py`

---

CHANGES.rst
nireports/assembler/data/__init__.py
pyproject.toml

Forgot that the whole cascade got held up because I wanted to get tox and workflow publication working here.

REL: 24.1.0

---

nireports/reportlets/mosaic.py

Most of this should be uncontroversial. I believe the type checker found a bug introduced in 60d04bf10dbc2fb5a085ee0726b1e0578408f584, and I fixed it in 7a3e146b7b17680af9b8d6fa316680531ff2a5bc, but I isolated it for review. The fixed lines are not exercised, which makes this a bit tenuous.

type: Annotate reportlets.mosaic

---

nireports/interfaces/reporting/base.py
nireports/interfaces/reporting/masks.py
nireports/reportlets/mosaic.py

Remove unused parameter in segmentation mosaic plot function.

ENH: Remove unused parameter in segmentation mosaic plot function

---

nireports/reportlets/mosaic.py

Prefer importing `warnings` for the sake of consistency with the rest of the code base.

STYLE: Prefer importing `warnings` for the sake of consistency

---

nireports/tests/test_reportlets.py

Remove duplicate local `NumPy` import in test function.

ENH: Remove duplicate local `NumPy` import in test function

---

.readthedocs.yaml
CHANGES.rst

Lots of small changes. The svgutils vendoring justifies a new minor release.

rel: 25.0.0

---

nireports/assembler/data/nipreps.json
nireports/assembler/report.py

STY: Spell out tracer entity

---

nireports/reportlets/modality/func.py
nireports/reportlets/nuisance.py

feat: Exclude non-steady-state volumes from confoundplot bounds, stats
