nipreps/nireports

.pre-commit-config.yaml, pyproject.toml
Adds a few touch ups to pre-commit
- Adds black profile to isort, to ensure compatibility between the two linters
- Adds isort to the pre-commit gauntlet
=> MAINT: Add black profile to isort, isort to pre-commit

nireports/assembler/data/default.yml, nireports/assembler/report.py
This PR removes one dictionary level in the configuration of plugins. This was already effected on the initialization via ``plugins`` argument of the ``Report``, but didn't work for the bootstrap file.
=> FIX: Plugin inclusion via main bootstrap file did not work

nireports/assembler/data/nipreps.json
Necessary for MRIQC's dwi results
=> ENH: Add a ``bval-<label>`` entity

nireports/interfaces/nuisance.py, nireports/reportlets/nuisance.py, nireports/tests/conftest.py, nireports/tests/test_interfaces.py
Related to https://github.com/nipreps/niworkflows/pull/843.
Changes proposed:
- Add an `ignore_initial_volumes` parameter to the `ConfoundsCorrelationPlot` interface.
- Add an `ignore_initial_volumes` parameter to the `confounds_correlation_plot` function.
=> Add `ignore_initial_volumes` param to `ConfoundsCorrelationPlot`

.circleci/config.yml, .github/workflows/build_test_deploy.yml, nireports/__init__.py, nireports/assembler/data/__init__.py, nireports/assembler/report.py, nireports/assembler/reportlet.py, nireports/assembler/tests/test_report.py, nireports/assembler/tools.py, pyproject.toml
Enable nireports to be installed and tested on Python 3.12, which no longer bundles setuptools in its virtual environments.
Apparently we're advertising 3.12 support without testing it... Adding that in.
Updating CircleCI, since we weren't installing the package there. I don't think we need the big Docker image.
=> RF: Purge pkg_resources, add data loader

CHANGES.rst, pyproject.toml
This will make some recent changes available to Nipreps releases, and it's been 6 months.
=> REL: 23.2.0

nireports/reportlets/mosaic.py, nireports/reportlets/nuisance.py
See https://github.com/nipreps/niworkflows/pull/866.
Fixes CI errors in https://github.com/nipreps/fmriprep/pull/3280.
=> MNT: Fix matplotlib.cm.get_cmap deprecation

nireports/interfaces/nuisance.py
ISC001 Implicitly concatenated string literals on one line
This rule is currently disabled because it conflicts with the formatter: https://github.com/astral-sh/ruff/issues/8272
=> STY: Apply ruff/flake8-implicit-str-concat rule ISC001

nireports/reportlets/nuisance.py
Set the `seaborn` barplot `hue` property value and set the `legend` property to `False`.
Fixes:
```
/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nireports/reportlets/nuisance.py:898:
FutureWarning:
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0.
Assign the `x` variable to `hue` and set `legend=False` for the same effect.
```
Fixes #89.
=> ENH: Set the `seaborn` barplot `hue` property value

nireports/interfaces/dmri.py, nireports/reportlets/modality/dwi.py
- DOC: Fix typos and grammar
- STYLE: Remove too many blank lines between functions
=> DOC: Misc documentation and style fixes

docs/conf.py, nireports/reportlets/modality/dwi.py
Fix `dwi` module function cross ref in docstring: provide the appropriate module where `draw_points` dwells.
Introduced inadvertently in commit 9f561d1 when the code was relocated from `eddymotion`.
Take advantage of the commit to improve the description of the method:
- Specify how the colors are assigned.
- Cross-reference the `draw_points` function using the Sphinx `seealso` tag.
- Use the tilde to shorten the link: display only the function name without the modules.
=> DOC: Fix `dwi` module function cross ref in docstring

nireports/reportlets/modality/dwi.py, nireports/reportlets/mosaic.py, nireports/reportlets/nuisance.py
A `cm.get_cmap()` snuck in since #98. To make clear that `colormaps` is not a local dictionary, I'm switching to using it from the `mpl` namespace.
=> RF: Consistently use matplotlib.colormaps in mpl namespace

README.rst
Make the coverage badge be last in the README badge list so that all CI badges are grouped together.
=> STYLE: Make coverage badge be last in README badge list

nireports/interfaces/__init__.py, nireports/interfaces/nuisance.py, nireports/reportlets/modality/dwi.py, nireports/reportlets/nuisance.py, nireports/tests/test_dwi.py, nireports/tests/test_interfaces.py, nireports/tests/test_reportlets.py, nireports/tests/utils.py
Add raincloud plot capabilities and demonstrate on the FA values of computed on a DWI volume across different tissue types.
=> ENH: Add raincloud plot capabilities

nireports/assembler/data/rating-widget/bootstrap.yml
=> FIX: Set max height and overflow css for qcrating widget

nireports/assembler/report.py, nireports/assembler/reportlet.py, pyproject.toml
Closes https://github.com/nipreps/nireports/issues/124.
Changes proposed:
- Add a section to embed PNGs and JPGs in the HTML report.
- Raise an exception if an extension isn't supported.
=> ENH: Support PNGs and JPGs in reportlets

nireports/assembler/tests/test_report.py, nireports/interfaces/dmri.py, nireports/interfaces/fmri.py, nireports/reportlets/modality/func.py, nireports/reportlets/nuisance.py, nireports/reportlets/surface.py, nireports/reportlets/utils.py, nireports/reportlets/xca.py, nireports/tests/test_dwi.py, nireports/tests/test_reportlets.py
At the same time, this PR ensures that all calls to ``plt.savefig()`` are followed by closing the figure.
Resolves: #129.
Closes: #130.
=> FIX: Address memory issues and corruption in ``fMRIPlot``

nireports/assembler/reportlet.py
Related to #124.
Changes proposed:
- Add `.gif` to the list of valid extensions.
=> Allow GIFs in reports

.circleci/config.yml, nireports/conftest.py, nireports/interfaces/reporting/masks.py, nireports/interfaces/reporting/registration.py, nireports/interfaces/reporting/segmentation.py, nireports/tests/conftest.py, nireports/tests/test_dwi.py, nireports/tests/test_interfaces.py, nireports/tests/test_interfaces_registration.py, nireports/tests/test_interfaces_segmentation.py, nireports/tests/test_interfaces_utils.py, nireports/tests/test_reportlets.py, nireports/tests/testing.py, nireports/tools/timeseries.py
This PR brings generalistic "reportlet capable" interfaces from niworkflows. It doesn't port those interfaces modified by niworkflows (e.g., the report-generating version of the normalization interface).
I'm a bit on the fence about this. Perhaps a cleaner way is to have a `nipreps.interfaces` namespace where packages can "contribute" their custom interfaces, where a set of default interfaces is available.
This would be consistent with @mgxd's idea of `nipreps.synthstrip` and so forth.
Also, splitting workflows and interfaces from niworkflows would probably be the best approach for clarity, and have niworkflows populate `nipreps.workflows` and nipreps-interfaces (or similar) populate `nipreps.interfaces`.
What do you think?
Resolves: #54.
=> ENH: Finalize migration of reporting interfaces

.github/workflows/build_test_deploy.yml, nireports/interfaces/reporting/registration.py, pyproject.toml, tox.ini
As a relatively small package, this seemed like a good place to start. As we add type annotations, mypy will ensure that we do it correctly.
cc @jhlegarreta
=> chore(types): Configure and run mypy checks in CI

nireports/reportlets/utils.py, nireports/tools/ndimage.py, nireports/tools/timeseries.py
This is an initial effort at annotating nireports. This does expose some gaps in the nibabel type stubs that will need to be addressed.
LMK what you think.
=> type: Annotate tools and reportlets.utils

nireports/reportlets/utils.py, nireports/tools/ndimage.py, nireports/tools/timeseries.py
Make type hinting compatible with Python 3.9: use `Union` instead of the pipe operator `|` to support type hints in Python 3.9. The pipe operator was overloaded for writing union types starting Python 3.10: https://peps.python.org/pep-0604/
https://docs.python.org/3.9/library/typing.html
https://docs.python.org/3.10/library/typing.html
Inadvertently let go through in commits 44d0ff6 and 8c18471.
=> ENH: Make type hinting compatible with Python 3.9

nireports/reportlets/mosaic.py, nireports/reportlets/utils.py
@jhlegarreta I meant to push this onto #150 after your comment but didn't get around to committing yesterday.
=> type: Relax Nifti1Image to SpatialImage

nireports/assembler/report.py, nireports/reportlets/modality/dwi.py, nireports/reportlets/mosaic.py
Copy the NIfTI image header of the primary source when creating another one from the former.
Make it conditional on the `nilearn` version as the warning is only being raised for `nilearn>=0.11`.
Fixes:
```
nireports/tests/test_interfaces_segmentation.py::test_SimpleShowMaskRPT
/home/runner/work/nireports/nireports/nireports/reportlets/mosaic.py:92:
FutureWarning: From release 0.13.0 onwards, this function will, by
default, copy the header of the input image to the output. Currently,
the header is reset to the default Nifti1Header. To suppress this
warning and use the new behavior, set `copy_header=True`.
bbox_nii: SpatialImage = nlimage.threshold_img(bbox_nii, 1e-3)  # type: ignore[no-redef]
```
raised for exmaple in:
https://github.com/nipreps/nireports/actions/runs/12681153218/job/353443 …
=> ENH: Copy NIfTI image header when creating from image

nireports/reportlets/mosaic.py, nireports/tests/test_reportlets.py
Fix mosaic plot `plot_sagittal` parameter warning: use a context manager to define the cases where errors or warnings are expected, and avoid the need for a partial function.
Fixes:
```
nireports/tests/test_reportlets.py::test_mriqc_plot_mosaic[True-views24]
nireports/tests/test_reportlets.py::test_mriqc_plot_mosaic[True-views26]
/home/runner/work/nireports/nireports/nireports/tests/test_reportlets.py:360:
UserWarning: Argument ``plot_sagittal`` for plot_mosaic() should not be used.
testfunc()
```
raised for example in:
https://github.com/nipreps/nireports/actions/runs/12681153218/job/35344304375#step:12:360
=> ENH: Fix mosaic plot `plot_sagittal` parameter warning

nireports/tests/test_reportlets.py
Close figures in test explicitly: when the `output_file` argument is `None` the `plot_carpet` method does not close figures, and thus a warning is raised if the number of open figures exceeds a given value.
Fixes:
```
nireports/tests/test_reportlets.py::test_carpetplot[linkage-0.7]
/home/runner/work/nireports/nireports/nireports/reportlets/nuisance.py:326:
RuntimeWarning: More than 20 figures have been opened.
Figures created through the pyplot interface (`matplotlib.pyplot.figure`)
are retained until explicitly closed and may consume too much memory.
(To control this warning, see the rcParam `figure.max_open_warning`).
Consider using `matplotlib.pyplot.close()`.
figure, allaxes = plt.subplots(figsize=(19.2, 10))
```
reported for example in: …
=> ENH: Close figures in test explicitly

nireports/reportlets/modality/dwi.py
Avoid divide by zero warnings when normalizing the DWI data: perform the division only in foreground voxels.
Fixes:
```
nireports/tests/test_dwi.py::test_nii_to_carpetplot_data
/home/runner/work/nireports/nireports/nireports/reportlets/modality/dwi.py:491: RuntimeWarning: invalid value encountered in divide
nii_data = nii_data / bzero[..., np.newaxis]
```
Raised for example in:
https://github.com/nipreps/nireports/actions/runs/12681153218/job/35344304375#step:12:339
=> ENH: Avoid divide by zero warnings when normalizing DWI data

nireports/tests/test_reportlets.py
Catch warning when loaded text file contains no data in test.
Fixes:
```
nireports/tests/test_reportlets.py::test_plot_melodic_components
/home/runner/work/nireports/nireports/nireports/reportlets/xca.py:128:
UserWarning: loadtxt: input contained no data:
"/tmp/pytest-of-runner/pytest-0/popen-gw0/test_plot_melodic_components0/noise_none.csv"
noise_components = np.loadtxt(noise_components_file, dtype=int, delimiter=",", ndmin=1)
```
raised for example in:
https://github.com/nipreps/nireports/actions/runs/12681153218/job/35344304375#step:12:347
=> ENH: Catch warning when loaded text file contains no data in test

nireports/tests/test_reportlets.py
Close all `Matplotlib` figures in relevant tests explicitly: when the `output_file` argument is `None` the `plot_carpet` method does not close figures, and thus a warning is raised if the number of open figures exceeds a given value.
Use `all` explicitly to guarantee all figures are closed. This change fixes the warnings that have persisted despite commits 626dd35 and 15f4898 claiming to fix these issues.
Fixes:
```
nireports/tests/test_reportlets.py::test_nifti_carpetplot
/home/runner/work/nireports/nireports/nireports/reportlets/nuisance.py:326:
RuntimeWarning: More than 20 figures have been opened.
Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are
retained until explicitly closed and may consume too much memory.
(To control this warning, see the rcParam …
```
=> ENH: Close all `Matplotlib` figures in relevant tests explicitly

nireports/tests/conftest.py, nireports/tests/test_reportlets.py
Use a fixture to close `Matplotlib` figures in tests.
Resolves #168.
=> ENH: Use a fixture to close `Matplotlib` figures in tests

.github/workflows/build_test_deploy.yml, .maint/ROADMAP.md, .pre-commit-config.yaml
Given that we're checking codespell in CI, we should add it to pre-commit.
=> chore: Update pre-commit config, add codespell

nireports/tests/conftest.py, nireports/tests/test_dwi.py, nireports/tests/test_reportlets.py
Prefer using NumPy's random number generator and the relevant random number sampling functions introduced in NumPy 1.17.0 over the legacy versions.
Add a fixture for tests to set the random number generator consistently across tests.
Specify the data type when creating the mask data for the DWI NIfTI to carpetplot data test to avoid:
```
Expected type 'ArrayLike', got 'floating[_16Bit]' instead
```
Documentation:
https://numpy.org/doc/2.2/reference/random/new-or-different.html#what-s-new-or-different
=> ENH: Prefer using NumPy's random number generator

docs/conf.py, nireports/_vendored/LICENSES/LICENSE.svgutils.txt, nireports/_vendored/svgutils/__init__.py, nireports/_vendored/svgutils/common.py, nireports/_vendored/svgutils/compose.py, nireports/_vendored/svgutils/templates.py, nireports/_vendored/svgutils/transform.py, nireports/assembler/misc.py, nireports/interfaces/mosaic.py, nireports/interfaces/reporting/masks.py, nireports/reportlets/modality/dwi.py, nireports/reportlets/mosaic.py, nireports/reportlets/nuisance.py, nireports/reportlets/utils.py, nireports/reportlets/xca.py, nireports/tests/test_interfaces.py, nireports/tests/test_interfaces_segmentation.py, pyproject.toml, tox.ini
Alternative to #170, and I think the more sustainable solution. If svgutils maintenance is ever resumed, we can consider unvendoring.
=> rf: Vendor svgutils into nireports._vendored

nireports/reportlets/nuisance.py, nireports/tests/test_reportlets.py
Fix deprecated `seaborn` function calls: use `displot` or `histplot` where applicable instead of `distplot`, since the latter will be removed in `seaborn` v0.14.0.
Adapt the corresponding calls where necessary adding reasonable keyword argument values.
Test histogram/distribution nuisance reportlet functions that use the affected functions.
Fixes:
```
This function has been deprecated and will be removed in seaborn v0.14.0.
It has been replaced by :func:`histplot` and :func:`displot`,
two functions with a modern API and many more capabilities.
```
Documentation:
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751
Fix the `mean_fd_hist` checks: use `is not None` as the default value is `None` and the parameter value is expected to be an array.
Fixes:
```
File …
```
=> MAINT: Update deprecated `seaborn` function calls before they error

nireports/reportlets/mosaic.py, nireports/tests/test_reportlets.py
Refactor the mosaic plot custom colormap creation to a separate method. Create a `matplotlib` `LinearSegmentedColormap` instance given a colormap name and a maximum alpha value. Avoids accessing the colormap instance's private `_lut` attribute.
Add the corresponding tests.
=> ENH: Refactor mosaic plot custom colormap creation

pyproject.toml
Fix `seaborn` and `matplotlib` orientation warning: `matplotlib` has deprecating the `vert` boolean orientation starting version 3.10.0. We are requiring `matplotlib` >= 3.5 and `seabornº >= 0.13.
`seaborn` supports `x` and `y` to specify the orientations starting version 0.13.0 and does an internal mapping to `matplotlib`'s `vertical` and `horizontal`:
https://github.com/mwaskom/seaborn/pull/3820/files#diff-42efb6918bd7e5f5a7b683aec2b32395b4ed303d3e2dae08f0e312171f7586ddR629
Map the `seaborn` `v` and `h` values to `x` and `y`, respectively, prior to calling the corresponding `seaborn` functions.
Fixes:
```
nireports/tests/test_interfaces.py: 4 warnings
nireports/tests/test_dwi.py: 1 warning
nireports/tests/test_reportlets.py: 12 warnings …
```
=> ENH: Fix `seaborn` and `matplotlib` orientation warning

.github/workflows/build_test_deploy.yml
Noticed when reviewing the CI from the release.
=> chore(ci): Update templateflow cache, use OIDC PyPI uploads

nireports/assembler/report.py
This PR closes #187 by adding PET information to the output_name_pattern, which is needed to generate reports for PET data.
=> ENH: Add output_name_pattern for PET

nireports/reportlets/modality/func.py
Closes #189.
Changes proposed:
- Add a new parameter, detrend, to the fMRIPlot class. The default is `True`, which matches previous behavior.
=> ENH: Add detrend parameter to fMRIPlot

pyproject.toml, tox.ini
py310-min wasn't being run properly after #192 because tox hadn't been updated. My bad.
I went ahead and adopted SPEC0+1yr. I made https://github.com/nipreps/speczeroplus/blob/main/spec-0000/chart.md to create the gantt chart rather than eyeballing the main page. I added nibabel and nilearn as well, so we only support a 3 year window of those tools.
=> chore: Update and test minimum dependencies

nireports/reportlets/modality/dwi.py, pyproject.toml
The default ruleset automatically excludes `E` rules that are not compatible with `ruff format`. Use `extend-select` over `select` to avoid such rules.
I cannot find a `C` ruleset. Rulesets that start with `C`:
* `COM` raises errors that seem spurious to me
* `C4`  raises no errors, so keep this ruleset
* `CPY` raises errors that I don't want to fix
* `C90` we disable the only error in this ruleset (`C901`) so it makes no sense keeping it
According to the Scientific Python Library Development Guide, `W` rules are not required if using a formatter:
https://learn.scientific-python.org/development/guides/style/#ruff
Finally, add `B` rules.
=> MNT: Update ruff parameters

.pre-commit-config.yaml
I was surprised pre-commit doesn't create autoupdate PRs.
It turns out [pre-comit.ci](https://pre-commit.ci/) is not enabled for this repository. Instead, pre-commit is run by the [pre-commit GitHub Action](https://github.com/pre-commit/action):
> this action is in maintenance-only mode and will not be accepting new features.
> 
> generally you want to use [pre-commit.ci](https://pre-commit.ci/) which is faster and has more features.
Created #212 for that.
=> MAINT: Update pre-commit hooks
